disabling code requiring the lxc to use a mount

diff --git a/lxc-ubuntu b/lxc-ubuntu
--- a/lxc-ubuntu
+++ b/lxc-ubuntu
@@ -311,14 +311,18 @@ create() {
     fi
 
     mkdir -p $rootfs
-    mount /dev/vg0/lxc-$utsname $rootfs
-    res=$?
 
-    if [ "$res" != "0" ]; then
-        echo "Failed to mount /dev/vg0/lxc-$utsname"
-        lxc-destroy -n $utsname
-        exit 1
-    fi
+    # old code to mount an "expected" device in preparation for putting a lxc in
+    # honestly seems a bit pointless so for now i'm just commenting it out
+    # TODO: refactor device mount management
+    #mount /dev/vg0/lxc-$utsname $rootfs
+    #res=$?
+
+    #if [ "$res" != "0" ]; then
+    #    echo "Failed to mount /dev/vg0/lxc-$utsname"
+    #    lxc-destroy -n $utsname
+    #    exit 1
+    #fi
 
     install_ubuntu
     write_ubuntu_hostname
